deactivated ES#326019
easysoftware/rys_management pull request #3
Opened 2020-02-08 21:03 UTC by ahorek

2020-02-10 15:12 UTC, ondra-m requested changes

2020-02-10 15:12 UTC, ondra-m commented on app/views/admin/rys_management/_view_admin_plugins_bottom.html.erb
> +          <% if plugin.active? %>
See my comments on rys plugin and next time write a link or say it requires modification from elsewhere.

2020-02-13 19:18 UTC, luk4s approved these changes

2020-02-14 05:44 UTC, ondra-m requested changes

2020-02-14 05:44 UTC, ondra-m commented on app/views/admin/rys_management/_view_admin_plugins_bottom.html.erb
> +            <% hosting_plugin = EasyHostingPlugin.find_by(plugin_name: plugin.plugin_id) %>
Padne na missing constant

2020-02-14 05:44 UTC, ondra-m commented on app/views/admin/rys_management/_view_admin_plugins_bottom.html.erb
> +            <% hosting_plugin = EasyHostingPlugin.find_by(plugin_name: plugin.plugin_id) %>
Co ten kód přesunout do vlastní partial, kterou hosting_service přepíšou?

2020-02-24 11:47 UTC, merged